### PR TITLE
Add CI configuration

### PR DESCRIPTION
**Pull request by bertsky**

### CODE REVIEW

**Review by kba — APPROVED** [review]
Looks good, I like the model cachng. Removing the comments from the makefile removes the help-autogenerate option but that's just a pet feature of mine.

**Comment by bertsky** [comment]
> Removing the comments from the makefile removes the help-autogenerate option but that's just a pet feature of mine.

You mean the `# pip install -r requirements.txt` annotations? I was not aware of this. I can of course revert those. Where can I see the output of that (generated) Makefile help?

**Comment by kba** [comment]
Through a combination of https://github.com/kba/shinclude for the macro processing and https://github.com/kba/makefile-parser for parsing makefile structure. I have that setup so I can regenerate help with a vim command. But don't waste time on this, in a simple makefile like this, there is little benefit over manual help section.

**Comment by bertsky** [comment]
Oh, I see. Now I know why you did not see a point in the _verbatim recipe_ approach for `help` – you always (re)generate this when it becomes non-trivial.

**Comment by bertsky** [comment]
Can you please follow this project on your CircleCI account?

**Comment by kba** [comment]
https://circleci.com/gh/OCR-D/workflows/ocrd_keraslm/tree/master

**Comment by bertsky** [comment]
Thanks!

**Pull request merged**
