### PR TITLE
Update assets (fix required for MacOS)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
The `assets` submodule was rather old and still had upper/lower case conflicts for case insensitive file systems.

**Comment by stweil** [comment]
I added a commit which fixes CircleCI partially, but there remain more CI issues which are unrelated to this pull request.

**Comment by bertsky** [comment]
@kba it seems the current `ocrd/tesserocr` is also not up-to-date (v0.13.5 instead of v0.13.6). Could you rebuild (or add that to ocrd_tesserocr's CI)?

Nevertheless, with all the difficulty just keeping track of ocrd_tesserocr changes here, I think we should remove that dependency and add our own version of the data (including OCR hypotheses) to assets.

**Review by bertsky — APPROVED** [review]

**Comment by kba** [comment]
> @kba it seems the current `ocrd/tesserocr` is also not up-to-date (v0.13.5 instead of v0.13.6). Could you rebuild (or add that to ocrd_tesserocr's CI)?

I've updated the PyPI release. If we want to keep the DockerHub releases, we need to also add this to the CI, since autobuilds have been disabled in the free tier of DH last year.

**Comment by kba** [comment]
> > @kba it seems the current `ocrd/tesserocr` is also not up-to-date (v0.13.5 instead of v0.13.6). Could you rebuild (or add that to ocrd_tesserocr's CI)?
> 
> I've updated the PyPI release. If we want to keep the DockerHub releases, we need to also add this to the CI, since autobuilds have been disabled in the free tier of DH last year.

I did not, 0.13.6 was already on PyPI. So you mean a new dockerhub release?

**Comment by bertsky** [comment]
Yes, I meant the DH release – sry.

**Pull request merged**
