### PR TITLE
replace deprecated ocrd workspace CLI constructs

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Review by bertsky — APPROVED** [review]

**Comment by bertsky** [comment]
@kba this is weird: CI now fails, but only on `master`, not on the PR branches. And it happens during CircleCI's `checkout` step, complaining:

```
error cloning repository: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

Has this anything to do with credentials (which I don't possess)?

**Comment by bertsky** [comment]
@kba could you find out anything about this? Did you try to retrigger CI yourself?

I only found [this issue](https://support.circleci.com/hc/en-us/articles/4410498350107-Build-Fails-due-to-SSL-Handshake) (which does not apply here, since our git in the env gets freshly installed)

**Comment by kba** [comment]
> @kba could you find out anything about this? Did you try to retrigger CI yourself?
> 
> I only found [this issue](https://support.circleci.com/hc/en-us/articles/4410498350107-Build-Fails-due-to-SSL-Handshake) (which does not apply here, since our git in the env gets freshly installed)

Finally fixed the issue by updating the circleci.yml to include a (large) resource_class in 787341d. That in turn made CircleCI add their key to the repo on GH and then the error went away. While debugging this, I also made a new and AFAICT redundant DockerHub release of `ocrd/tesserocr` under the assumption that the git in that repo was out-of-date. Apparently ocrd_keraslm was never properly set up with CircleCI but why that is and why updating the config triggered some kind of cache invalidation while your changes to the circleci.yml did not, I have no idea.

**Comment by bertsky** [comment]
> Finally fixed the issue by updating the circleci.yml to include a (large) resource_class in [787341d](https://github.com/OCR-D/ocrd_keraslm/commit/787341d89424868be09452638e45f26fbd2f196b). That in turn made CircleCI add their key to the repo on GH and then the error went away. While debugging this, I also made a new and AFAICT redundant DockerHub release of `ocrd/tesserocr` under the assumption that the git in that repo was out-of-date. Apparently ocrd_keraslm was never properly set up with CircleCI but why that is and why updating the config triggered some kind of cache invalidation while your changes to the circleci.yml did not, I have no idea.

Wow. Complexity, perplexity. Thanks for fighting it through!

**Pull request merged**
