### PR TITLE
character-level processing, context conditioning, underspecification

### PR DESCRIPTION
**Pull request by bertsky**
This is a major update, intended to bring better usability and adequacy.

### CODE REVIEW

**Review by wrznr — APPROVED** [review]
Thanks a lot for your efforts. Two thoughts:
1. Think about smaller PRs. Reviewing is not possible with this amount of changes.
2. Maybe we should split core functionality and the ocr-d wrapping into two separate repositories.

**Comment by bertsky** [comment]
>     1. Think about smaller PRs. Reviewing is not possible with this amount of changes.

I agree. But then, with that much time passing before merges, how can I do that? AFAICS, Github still has no [stacked/dependent PRs](https://github.com/isaacs/github/issues/867).

>     2. Maybe we should split core functionality and the ocr-d wrapping into two separate repositories.

Could you elaborate on that? What would be to gain, what kind of interface/dependency would be erected between them? (I don't think there are other many LMs we could wrap in the same way: based on lattices, and decoding incrementally. But perhaps I am wrong...)

**Comment by wrznr** [comment]
> What would be to gain, what kind of interface/dependency would be erected between them?

I think about the *possible* integration into other OCR software (i.e. Tesseract). The interface would depend on their architecture.

Can you merge this PR?

**Comment by bertsky** [comment]
> I think about the _possible_ integration into other OCR software (i.e. Tesseract). The interface would depend on their architecture.

Oh I see. Well, the lattice interface based on `networkx.DiGraph` as currently defined by `lib.rating.rate_best` and `lib.rating.next_path` _is_ independent of OCR-D workspace/processor and METS/PAGE. It is already used in [cor-asv-fst](https://github.com/ASVLeipzig/cor-asv-fst) incrementally, but can also be used in a non-incremental fashion (for the CLI interface, public version coming up). It could be made more general and prominent... As for Tesseract integration, we would have to find a good way for C [embedding](https://docs.python.org/2/extending/embedding.html) first. Maybe the LM could be integrated somewhere in the beam search.

Another option would be to integrate [cor-asv-ann](https://github.com/ASVLeipzig/cor-asv-ann), BTW. In theory, it could use the undecoded matrix as interface.

> Can you merge this PR?

As soon as @kba fixes the [remaining](https://github.com/OCR-D/core/issues/176) [issues](https://github.com/OCR-D/core/issues/96) with core 1.0 beta, yes. (0.15.2 is defunct too.)

**Review by kba — APPROVED** [review]

**Comment by bertsky** [comment]
I have (reluctantly) migrated to core 1.0 despite the open issues – but seem to have fought down one of them.

**Pull request merged**
